add_newline = false

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
# 当进入 Vi Normal 模式时，图标变色或改变
vimcmd_symbol = "[VIM](bold Bezier) ➜"

[python]
symbol = "🐍 "
pyenv_prefix = "venv "
# 只有在检测到虚拟环境或 .py 文件时才显示
style = "yellow bold"

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
