# 1. 别换行，省地方
add_newline = false

# 2. 保持符号简单，不去监听复杂的 Vim 模式切换
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

# 3. 只有在虚拟环境里才显示 Python，平时藏起来
[python]
detect_extensions = []
